[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 35 }
decorations = "Buttonless"
opacity = 0.93
blur = false 
dynamic_padding = true
dynamic_title = true
padding = { x = 4, y = 4 }
option_as_alt = "Both"
startup_mode = "Windowed"
resize_increments = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 16
